### ISSUE TITLE
Consider using integer claim keys and CBOR labels over string claim keys and CBOR labels

### ISSUE THREAD

**Issue by awoie** [oauth-wg/draft-ietf-oauth-status-list#122] opened 2024-03-13 19:39 UTC
To be more compact, it might be worth thinking about the option to allow integer labels for lst and bits instead of string labels.

**Comment by paulbastian** [comment] 2024-03-20 23:26
Possible duplicate of #116

**Closed** 2024-04-02 06:19 UTC
